image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install roots -g
  - npm install
  - roots compile -e production
  artifacts:
    paths:
    - public
  only:
    - master
